[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source $DOTFILES_DIR/nvim/plugins/nerdtree.vim'

[[plugins]]
repo = 'Shougo/neocomplcache'
hook_add = 'source $DOTFILES_DIR/nvim/plugins/neocomplcache.vim'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'itchyny/landscape.vim'

[[plugins]]
repo = 'bling/vim-airline'
hook_add = 'source $DOTFILES_DIR/nvim/plugins/airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = 'source $DOTFILES_DIR/nvim/plugins/indent.vim'


[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'w0rp/ale'
