[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'itchyny/landscape.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
